title: Thanh-Tung Ngo (Tom)
url: "https://tungngovn.github.io"
baseurl: ""

# remote_theme: daattali/beautiful-jekyll
remote_theme: ankitsultana/researcher@gem
# layout: "default"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/tungngovn"
footer_text: "Personal website of Thanh-Tung Ngo"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/tungngovn.github.io"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Research"
   link: "/pages/research"
 - name: "Social activities"
   link: "/pages/social"
 - name: "Contact"
   link: "/pages/contact"
