title: Thanh-Tung_Ngo
url: "https://tungngovn.github.io"
baseurl: "/tungngovn.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/tungngovn"
footer_text: "Personal website of Thanh-Tung Ngo"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
#  - name: "Research"
  #  link: "research"
#  - name: "Social activities"
  #  link: "social"
